### ISSUE TITLE
helm-projectile-find-file does'nt create files.

### ISSUE THREAD

**Issue by fahrradflucht** [bbatsov/helm-projectile#42]
When using `projectile-find-file` I can create a file by entering a path relative to the project root and hitting <RET>.

With `helm-projectile-find-file` it just happens nothing.

**Comment by nloyola** [comment]
Can you please clarify how you get `projectile-find-file` to create a file for you. I can't get it to work with  `projectile-20170106.606`.

**Comment by Fahrradflucht** [comment]
Sorry I can't help you. I don't use emacs anymore. At the time I wrote this, it worked like I described.

**Comment by xiongtx** [comment]
This is due to Helm handling non-matching input differently from `ido`, which is what `projectile-completion-system` defaults to. The same problem occurs without `helm-projectile` when `projectile-completion-system` is set to `'helm`.

When the user hits `RET` with non-matching input, Helm exits without executing any actions, because there is no selected candidate on which an action can be executed.

`helm-find-files` *does* create a new file buffer when non-matching input is given, as does `helm-buffers-list` with buffers, albeit in different ways. I've posted a [question on the Helm Google Group](https://groups.google.com/forum/#!topic/emacs-helm/pMZybaiVWHk) r.e. the best way to implement this.
