### ISSUE TITLE
There is no changelog

### ISSUE THREAD

**Issue by svetlyak40wt** [bbatsov/helm-projectile#6]
For example, what is difference between 0.12 which I have and 0.13?

**Comment by bbatsov** [comment]
Guess @xiongtx will tackle this eventually.

**Comment by svetlyak40wt** [comment]
If you'll tag release commits with 0.1.2 tags, then my tool AllMyChanges.com will build a changelog automatically: https://allmychanges.com/p/emacs/helm-projectile/

Handwritten release notes are better though.

**Comment by bbatsov** [comment]
Yeah, I agree. Automatically generated changelogs usually are not very useful because they just dump a bunch of commit messages into a file. Some tools require conventions for the format of the commit messages so they'd know which commits to include in which section of the changelog but this also requires extra work.

**Comment by svetlyak40wt** [comment]
At my daily job, we have agreement, that each pull-request should update a changelog and we are using [python-releases](https://pypi.python.org/pypi/releases) to generate nice human readable changelog.

Actually, we use additional trick to make few parallel pulls don't conflict when changing changelog data. Each change log adds a small file in `changelog.d` directory. When new version is released, a small script:
```
@task
def prepare_changelog(ctx, unlink=True):
    new_items = []
    base = 'changelog.d'
    if os.path.exists(base):
        for filename in os.listdir(base):
            if filename.startswith('README'):
                continue

            full_path = os.path.join(base, filename)
            with open(full_path) as f:
                new_items.append(
                    f.read().strip() + '\n'
                )
            if unlink:
                run('git rm ' + full_path)

    with open('ChangeLog.rst') as f:
        changelog_lines = f.readlines()

    changelog_lines[3:3] = new_items

    with open('ChangeLog.rst', 'w') as f:
        f.writelines(changelog_lines)

    # now we'll commit changes
    run('git add ChangeLog.rst')
    run('git commit -m "ChangeLog.rst was updated."')
```
is executed and followed by `bumpversion minor`. It is another useful utility for changing version number in many places: https://pypi.python.org/pypi/bumpversion.

If you don't mind of using python based tools in release process, I could help here and make a pull-request with all necessary scripts.

**Comment by xiongtx** [comment]
Automated scripts are way overkill for a small project like this that's had <50 commits in over a year.

Most Emacs users don't even bother downloading specific package versions--MELPA just provide the latest version of a package, which sometimes (or frequently, in the case of Helm :smirk:) breaks things.

**Comment by svetlyak40wt** [comment]
And what is the best way to find what was the reason of the breaking?

**Comment by xiongtx** [comment]
If it's something upstream (i.e. `helm` or `projectile`, which is usually the case for a "wrapper" package like this), a changelog for `helm-projectile` wouldn't tell you anything useful about why it broke.

If it's `helm-projectile` itself, a quick look at the last few commit messages since you last updated the package should tell you that.
