### ISSUE TITLE
Should helm-projectile-find-file swallow errors?

### ISSUE THREAD

**Issue by IvanMalison** [bbatsov/helm-projectile#92]
helm-projectile-find-file swallows errors, but I'm struggling to figure out why it should do this.

https://github.com/bbatsov/helm-projectile/blob/0e9ba276b3fbc420b8cbdc1b99262ccd5c750db7/helm-projectile.el#L502

What advantage does this confer? In my case it covered up an error that had to do with how I had configured emacs and resulted in an empty file list when attempting to open a file.

**Comment by xiongtx** [comment]
I'd guess it's because `projectile-project-root` [signals an error](https://github.com/bbatsov/projectile/blob/1d580684c0efa100c7206a0fe6fc63e47fc49da1/projectile.el#L941) when you're not inside a project and [`projectile-require-project-root`](https://github.com/bbatsov/projectile/blob/1d580684c0efa100c7206a0fe6fc63e47fc49da1/projectile.el#L196) is non-nil.

You can see similar uses of `condition-case` (which really should be `ignore-errors`, since that's a built-in macro) in Projectile itself.

I'm not sure that showing the user an empty buffer is better than informing the they're not in a project though--what do you think, @IvanMalison & @bbatsov?
